title: Rails Cron Documentation
description: >-
  Documentation for Rails Cron - A robust solution for scheduling and managing cron jobs in Ruby on Rails applications.
baseurl: ""
domain: rails_cron.codevedas.com
repository: Code-Vedas/rails_cron
# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - kramdown
mermaid:
  version: 10.1.0
callouts:
  note:
    title: Note
    color: blue
toc:
  depth: 2
  min_heading_level: 2
  max_heading_level: 3
aux_links:
  - title: " ğŸŒ™ / â˜€ï¸ "
    url: javascript:toggleTheme();
    new_tab: false
  - title: Repository
    url: https://github.com/Code-Vedas/rails_cron
    new_tab: true
aux_links_new_tab: true
nav_enabled: true
heading_anchors: true
